### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Ca5imoo** [geeks-r-us/maxstorage_ultimate#7]
I have been using the integration for 2 weeks and it worked great until recently. Since then, however, I have had to assign my own password (user, could not be changed, only the password). I can no longer establish a connection. When I enter the password, all I get is: Unexpected error. What could be the reason for this?

![2024-05-04 11_45_18-Einstellungen – Home Assistant](https://github.com/geeks-r-us/maxstorage_ultimate/assets/157792785/c6d55ec2-6de0-4cda-8b78-f8e7ead7e68d)

**Comment by geeks-r-us** [comment]
Hi, 

to have an idea what's going wrong can you attach the output of the logs. 
Settings > System > Logs  here should be an Error entry with more details of what happened.

Thx for reporting

**Comment by Ca5imoo** [comment]
Hello,

the only error entry I have found is this one:

This error was caused by a custom integration

Logger: custom_components.maxstorage_ultimate.config_flow
Quelle: custom_components/maxstorage_ultimate/config_flow.py:63
Integration: maxstorage_ultimate (Dokumentation, Probleme)
Erstmals aufgetreten: 11:38:35 (3 Vorkommnisse)
Zuletzt protokolliert: 11:40:41

Unexpected exception: 'Ident'

It seems to me that when a user logs in, the password is replaced with the default value and therefore no connection is established. but unfortunately I'm not that deep into it that I would understand the scripts

**Comment by geeks-r-us** [comment]
Looks like it wasn't able to grab the device ident.
There could be 2 reasons. Login failed but it was not detected correctly as AuthFailed 
Or you have a newer portal version and they have changed the location of the data. 

Can you provide me the software version running on your MaxStorage? You find it by klicking on the ? in the top bar.
I have 3.4.0 running on mine.

**Comment by Ca5imoo** [comment]
the update was also the reason why the default password had to be changed.
Firmware-Version: 3.4.3
Hardware-Version: MCv2.0 Serie

Changelog firmware 3.4.3:
Good news: Your AMPERE.Storage has received an update.
Functions:
Heat pumps: The control of heat pumps is now possible. At the start, iDM heat pumps will be controllable with the Navigator 2.0.
Wallbox with phase switching: Keba wallboxes can now be controlled with phase switching in the beta test.

Improvements:
Backup power mode: The backup power mode has been further optimized. In addition, a battery backup can now be set.

Bug fixes:
Heating rod control: In some cases, heating rods were not controlled correctly in 'Feed-in power' control mode.
Energy history for swarm systems: The energy history for swarm systems now shows the correct sum of all devices again.
Various bug fixes: Some errors have been fixed.

**Comment by geeks-r-us** [comment]
Ok then I can happily await the new features to arrive on my device.

But this will not fix your issue on fast track... 
Would you mind share a saved html  of the home site ?

**Comment by Ca5imoo** [comment]
Could you give me an e-mail address where I can send the files?

**Comment by geeks-r-us** [comment]
sure 
root@geeks-r-us.de

**Comment by geeks-r-us** [comment]
I improved robustness of device data parsing. 
Can you try it? 
It's located here: https://github.com/geeks-r-us/maxstorage_ultimate/tree/device_data_parsing
Only change is in client.py

**Comment by Ca5imoo** [comment]
I will try it out, but I won't be home again until Thursday.

**Comment by Ca5imoo** [comment]
When configuring the login, the situation remains unchanged...unexpected error with "user" & "own password"

**Comment by geeks-r-us** [comment]
I think then something I used for matching is not available in raw html and is applied first when style is applied via javascript.
I've extended the logging so it should dump the received raw html. Could you provide these by mail?

**Comment by Ca5imoo** [comment]
Now I need some help, what exactly should I do or how do I get the raw HTML? We're talking about the raw HTML from the system's web portal, right?

**Comment by geeks-r-us** [comment]
Solarmax relased now 3.4.4 for their own customers. Version 0.0.2 works with this.
Please check if it's also working for Ampere users

**Comment by Ca5imoo** [comment]
the new version works very well. thank you very much but where was the error after the update?

**Comment by geeks-r-us** [comment]
added some code optimizations and thanks to your input made the data reading more stable.
I guess we can mark this as solved.

**Comment by Ca5imoo** [comment]
Tanks for All
